/*
 * Universidad Politécnica de San Luis Potosí
 * Programación III Java 
 * Programación Orientada a Objetos
 */
package empleado;
import excepciones.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * JFrame que proporciona al usuario información del empleado y permite modificarlo
 * @author Ana Sofía Rodríguez Castillo, 178815@upslp.edu.mx
 * @author Ana Sofía Rodriguez Castillo
 * @author 178815@upslp.edu.mx
 * @version 1.0
 */
public class ModificaEmpleado extends javax.swing.JFrame {
    
    /**
     * Representa la conexión
     */
    private final Connection con;
    /**
     * Variable que guarda el id del empleado
     */
    private int registro;
    /**
     * Variable de para el correo anteriormente registrado
     */
    String correoTemp;
    /**
     * Variable de tipo empleado
     */
    private final Empleado empleado;
    
    class FondoPanel extends javax.swing.JPanel{
        private java.awt.Image imagen;
        
        @Override
        public void paint(java.awt.Graphics g){
            imagen = new javax.swing.ImageIcon(//img\\Inicio.gif
            getClass().getResource("/imgEmpleado/ModificaEmpleado.png")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }

    /**
     * Creates new form ModificaEmpleado
     * Crea una instancia de la Clase ModificaEmpleado
     * Inicializa algunos de los valores que aparecen en el pane
     * Establece la posicion del pane
     * @param con Conexión
     */
    public ModificaEmpleado(Connection con) {
        this.con = con;
        empleado = new Empleado(this.con);
        initComponents();
        actualizaTabla();
        empleado.obtenerIdEmpleado();
        txtIdEmpleado.setModel(new javax.swing.DefaultComboBoxModel(empleado.getIdEmpleado()));
//        txtCorreo.setEditable(false);
        this.setTitle("Modifica Empleado");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtIdEmpleado = new javax.swing.JComboBox<>();
        txtRol = new javax.swing.JComboBox<>();
        txtEstado = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Datos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });

        txtIdEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtIdEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmpleadoActionPerformed(evt);
            }
        });

        txtRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrega", "Registro" }));

        txtEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Datos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnGuardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtIdEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombre)
                                .addComponent(txtDireccion)
                                .addComponent(txtTelefono)
                                .addComponent(txtCorreo)
                                .addComponent(txtRol, 0, 170, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnGuardar)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmpleadoActionPerformed
        registro = Integer.parseInt(txtIdEmpleado.getSelectedItem().toString());
        String resul[] = empleado.consultaEmpleado(registro);
        txtNombre.setText(resul[0]);
        txtDireccion.setText(resul[1]);
        txtTelefono.setText(resul[2]);
        correoTemp = resul[3];
        txtCorreo.setText(resul[3]);
        txtRol.setSelectedItem(resul[4]);
        txtEstado.setSelectedItem(resul[4]);
    }//GEN-LAST:event_txtIdEmpleadoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{
            if(txtNombre.getText().equals("") || txtDireccion.getText().equals("") || txtTelefono.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Faltan datos por llenar");
            }else{
                registro = Integer.parseInt(txtIdEmpleado.getSelectedItem().toString());
                empleado.modificaEmpleado(registro, txtNombre.getText(), txtCorreo.getText(), txtDireccion.getText(), txtTelefono.getText(), txtRol.getSelectedItem().toString(), txtEstado.getSelectedItem().toString());
                JOptionPane. showMessageDialog(this,"Registro modificado");
                actualizaTabla();
            }  
        }catch(Exception err){
            
        }finally{
            txtNombre.setText("");
            txtCorreo.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            actualizaTabla();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        try{
            correoR();
        }catch(CorreoRepetidoException  e){
            String correoExistente = e.getCorreoExistente();
            int opcionSeleccionada = JOptionPane.showOptionDialog(
                null,
                "El correo ya existe. ¿Qué deseas hacer?",
                "Correo existente",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new Object[]{"Conservar anterior", "Crear nuevo"},
                "Conservar anterior"
            );

            if (opcionSeleccionada == 0) {
                JOptionPane.showMessageDialog(null, e.getMessage() + "\n Lo regresaremos a su valor original", "Advertencia", JOptionPane.WARNING_MESSAGE);
                txtCorreo.setText(correoTemp);
            } else if (opcionSeleccionada == 1) {
                JOptionPane.showMessageDialog(null, e.getMessage() + "\n Le asignaremos un nuevo correo", "Advertencia", JOptionPane.WARNING_MESSAGE);
                txtCorreo.setText(empleado.correo(txtNombre.getText(), txtIdEmpleado.getSelectedItem().toString()));
            }
            
            
        }
    }//GEN-LAST:event_txtCorreoFocusLost

    /**
     * funcion busca repeticiones del correo
     * consulta sql que excluye el correo del registro implicado
     * @throws CorreoRepetidoException excepción propia
     */
    public void correoR() throws CorreoRepetidoException{
        
        try {
            Statement sts = con.createStatement();
            //sentencia que excluye los registros con cierto id de empleado
            String consulta = "SELECT * FROM empleado WHERE idEmpleado <> " + registro + "";
            ResultSet rs = sts.executeQuery(consulta);
            
            while(rs.next()){
                if(rs.getString("correo").equals(txtCorreo.getText())){
                        throw new CorreoRepetidoException(rs.getString("correo"));
                }
            }
        } catch (SQLException ex) {
            System.out.println(ex.getNextException());
        }
    }
    
    /**
     * Función que actualiza la tabla del empleado, usando la variable de nombre Datos
     */
    public final void actualizaTabla(){
        DefaultTableModel modelo = empleado.actualizaTablaEmpleado();
        this.Datos.setModel(modelo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
    * Tabla en la que aparecen las consultas
    */
    private javax.swing.JTable Datos;
    /**
    * boton que llama al método de modificación
    */
    private javax.swing.JButton btnGuardar;
    /**
    * panel de fondo
    */
    private javax.swing.JPanel jPanel1;
    /**
    * scroll panel
    */
    private javax.swing.JScrollPane jScrollPane1;
    /**
    * textfield para modificar correo
    */
    private javax.swing.JTextField txtCorreo;
    /**
    * textfield para modificar dirección
    */
    private javax.swing.JTextField txtDireccion;
    /**
    * combo box para elegir estado
    */
    private javax.swing.JComboBox<String> txtEstado;
    /**
    * combo box para elegir id de empleado
    */
    private javax.swing.JComboBox<String> txtIdEmpleado;
    /**
    * textfield para modificar nombre
    */
    private javax.swing.JTextField txtNombre;
    /**
    * combo box para elegir rol
    */
    private javax.swing.JComboBox<String> txtRol;
    /**
    * textfield para modificar teléfono
    */
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
