/*
 * Universidad Politécnica de San Luis Potosí
 * Programación III Java
 * Programación Orientada a Objetos
 * @author Ana Sofía Rodríguez Castillo, 178815@upslp.edu.mx
 */
package paquete;
import empleado.*;

import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

/**
 * JFrame que proporciona al usuario información de los paquetes que son asignados a cierto empleado
 * @author Ana Sofía Rodríguez Castillo, 178815@upslp.edu.mx
 * @author Ana Sofía Rodriguez Castillo
 * @author 178815@upslp.edu.mx
 * @version 1.0
 */
public class ConsultaPktXEmpleado extends javax.swing.JFrame {
    /**
     * Representa la conexión
     */
    private final Connection con;
    /**
     * Variable de tipo paquete
     */
    private final Paquete paquete;
    /**
     * Variable de tipo empleado
     */
    private final Empleado empleado;
    /**
     * Variable para almacenar temporalmente el id de empleado
     */
    private int idEmpleado;
    
    class FondoPanel extends javax.swing.JPanel{
        private java.awt.Image imagen;
        
        @Override
        public void paint(java.awt.Graphics g){
            imagen = new javax.swing.ImageIcon(
            getClass().getResource("/imgPkt/ConsultaPktXEmpleado.png")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }

    /**
     * Creates new form ConsultaPkt
     * Crea una instancia de la clase 
     * Inicializa algunos de los valores que aparecen en el pane
     * Establece la posicion del pane
     * @param con Conexión
     */
    public ConsultaPktXEmpleado(Connection con) {
        this.con = con;
        empleado = new Empleado(this.con);
        paquete = new Paquete(this.con);
        initComponents();
        actualizaTabla(0);
        
        empleado.obtenerIdEmpleado();
        txtIdEmpleado.setModel(new javax.swing.DefaultComboBoxModel(empleado.getIdEmpleado()));
        
        this.setTitle("Paquetes por Empleado");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        Datos = new javax.swing.JScrollPane();
        Datoss = new javax.swing.JTable();
        txtIdEmpleado = new javax.swing.JComboBox<>();
        btnTodos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        /**
        * Formato de la tabla
        */
        Datoss.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        /**
        * view port
        */
        Datos.setViewportView(Datoss);

        /**
        * se define la fuente y propiedades
        */
        txtIdEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        /**
        * evento accionado
        */
        txtIdEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmpleadoActionPerformed(evt);
            }
        });

        /**
        * se define la fuente y propiedades
        */
        btnTodos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        /**
        * texto que aparece en pantalla
        */
        btnTodos.setText("Todos los paquetes");
        /**
        * evento accionado
        */
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Id Empleado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTodos)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnTodos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmpleadoActionPerformed
        idEmpleado = Integer.parseInt(txtIdEmpleado.getSelectedItem().toString());
        actualizaTabla(1);
        Archivo objArchivo1 = new Archivo(con,idEmpleado,2);
        Archivo objArchivo2 = new Archivo(con,idEmpleado,2);
        objArchivo1.setPriority(1);
        objArchivo2.setPriority(10);
        objArchivo1.start();
        objArchivo2.start();
    }//GEN-LAST:event_txtIdEmpleadoActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        Archivo objArchivo1 = new Archivo(con,1);
        Archivo objArchivo2 = new Archivo(con,1);
        objArchivo1.setPriority(1);
        objArchivo2.setPriority(10);
        objArchivo1.start();
        objArchivo2.start();
        actualizaTabla(0);
    }//GEN-LAST:event_btnTodosActionPerformed

    /**
     * la función filtra el tipo de consulta que se quiere realizar
     * si el valor es cero se muestran todos los paquetes registrados
     * @param op opcion de consulta 1 consulta por empleado
     * opcion 0 consulta general
     */

    public final void actualizaTabla(int op){
        DefaultTableModel modelo;
        if(op != 0){
             modelo = paquete.actualizaTablaPaquete("empleado", "", idEmpleado);
        }else{
             modelo = paquete.actualizaTablaPaquete("", "", 0);
        }
        this.Datoss.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
    * Tabla en la que aparecen las consultas
    */
    private javax.swing.JScrollPane Datos;
    /**
    * Tabla en la que aparecen las consultas
    */
    private javax.swing.JTable Datoss;
    /**
    * boton que llama al método de consulta general
    */
    private javax.swing.JButton btnTodos;
    /**
    * texto del id de empleado
    */
    private javax.swing.JLabel jLabel1;
    /**
    * panel de fondo
    */
    private javax.swing.JPanel jPanel1;
    /**
    * combo box para elegir id de empleado
    */
    private javax.swing.JComboBox<String> txtIdEmpleado;
    // End of variables declaration//GEN-END:variables
}
