/*
 * Universidad Politécnica de San Luis Potosí
 * Programación III Java
 * Programación Orientada a Objetos
 * @author Ana Sofía Rodríguez Castillo, 178815@upslp.edu.mx
 */
package paquete;

import cliente.Cliente;
import empleado.Empleado;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * JFrame que proporciona al usuario información del paquete y algunos espacios para modificarlos
 * @author Ana Sofía Rodríguez Castillo, 178815@upslp.edu.mx
 * @author Ana Sofía Rodriguez Castillo
 * @author 178815@upslp.edu.mx
 * @version 1.0
 */
public class ModificaPkt extends javax.swing.JFrame {
    /**
     * Representa la conexión
     */
    private final Connection con;
    /**
     * Variable de tipo paquete
     */
    private final Paquete paquete;
    /**
     * Variable de tipo cliente
     */
    private final Cliente clienteRef;
    /**
     * Variable de tipo empleado
     */
    private final Empleado empleadoRef;
    /**
     * Variable para almacenar temporalmente el id de empleado
     */
    private int idEmpleado;
    /**
     * Variable para almacenar temporalmente el id de cliente
     */
    private int idCliente;
    /**
     * Variable para almacenar temporalmente el id de paquete
     */
    private int idPkt;
    /**
     * Variable para retornar la palabra clave
     */
    private String pclave;
    
    class FondoPanel extends javax.swing.JPanel{
        private java.awt.Image imagen;
        
        @Override
        public void paint(java.awt.Graphics g){
            imagen = new javax.swing.ImageIcon(//img\\Inicio.gif
            getClass().getResource("/imgPkt/ModificaPkt.png")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }

    /**
     * Creates new form ModificaPkt
     * Se crea una instancia de la clase ModificaPkt
     * Inicializa algunos de los valores que aparecen en el pane
     * Establece la posicion del pane
     * @param con Conexion
     */
    public ModificaPkt(Connection con) {
        this.con = con;
        empleadoRef = new Empleado(this.con);
        paquete = new Paquete(this.con);
        clienteRef = new Cliente(this.con);
        initComponents();
        actualizaTabla();
        
        paquete.obtenerIdPaquete();
        txtIdPkt.setEditable(false);
        txtIdPkt.setModel(new javax.swing.DefaultComboBoxModel(paquete.getIdPaquete()));
        
        clienteRef.obtenerIdCliente("Activo");
        txtIdCliente.setModel(new javax.swing.DefaultComboBoxModel(clienteRef.getIdCliente()));
        
        empleadoRef.obtenerIdEmpleado("Activo");
        txtIdEmpleado.setModel(new javax.swing.DefaultComboBoxModel(empleadoRef.getIdEmpleado()));
        
        this.setTitle("Modifica Paquete");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        txtIdEmpleado = new javax.swing.JComboBox<>();
        txtIdCliente = new javax.swing.JComboBox<>();
        txtNomCliente = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtPClave = new javax.swing.JTextField();
        txtEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Datos = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        txtIdPkt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtIdEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtIdCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "En proceso", "Entregado" }));

        Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Datos);

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtIdPkt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtIdPkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPktActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btnGuardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdEmpleado, 0, 190, Short.MAX_VALUE)
                            .addComponent(txtIdCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNomCliente)
                            .addComponent(txtDireccion)
                            .addComponent(txtPClave)
                            .addComponent(txtEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdPkt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(98, 98, 98)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(txtIdPkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtPClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnGuardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{
            if(txtNomCliente.getText().equals("") || txtDireccion.getText().equals("") || txtPClave.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Faltan datos por llenar");
            }else{
                idEmpleado = Integer.parseInt(txtIdEmpleado.getSelectedItem().toString());
                idCliente = Integer.parseInt(txtIdCliente.getSelectedItem().toString());
                paquete.modificaPaquete(idPkt, txtDireccion.getText(), txtEstado.getSelectedItem().toString(), txtPClave.getText(), idCliente, txtNomCliente.getText(),idEmpleado );
                JOptionPane. showMessageDialog(this,"Registro modificado");
                actualizaTabla();
            }  
        }catch(Exception err){
            
        }finally{
            txtNomCliente.setText("");
            txtPClave.setText("");
            txtDireccion.setText("");
            actualizaTabla();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtIdPktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPktActionPerformed
        idPkt = Integer.parseInt(txtIdPkt.getSelectedItem().toString());
        String resul[] = paquete.consultaPaqueteS(idPkt);
        
        txtIdCliente.setSelectedItem(resul[1]);
        txtIdEmpleado.setSelectedItem(resul[2]);
        txtNomCliente.setText(resul[3]);
        txtDireccion.setText(resul[4]);
        txtPClave.setText(resul[5]);
        txtEstado.setSelectedItem(resul[6]);
    }//GEN-LAST:event_txtIdPktActionPerformed

    /**
     * Función que actualiza la tabla del paquete, usando la variable de nombre Datos
     */
    public final void actualizaTabla(){
        DefaultTableModel modelo = paquete.actualizaTablaPaquete("", "", 0);
        this.Datos.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
    * Tabla en la que aparecen las consultas
    */
    private javax.swing.JTable Datos;
    /**
    * boton que llama al método de modificaión
    */
    private javax.swing.JButton btnGuardar;
    /**
    * panel de fondo
    */
    private javax.swing.JPanel jPanel1;
    /**
    * scroll panel
    */
    private javax.swing.JScrollPane jScrollPane1;
    /**
    * textfield para modificar dirección
    */
    private javax.swing.JTextField txtDireccion;
    /**
    * combo box para elegir estado
    */
    private javax.swing.JComboBox<String> txtEstado;
    /**
    * combo box para elegir id cliente
    */
    private javax.swing.JComboBox<String> txtIdCliente;
    /**
    * combo box para elegir id empleado
    */
    private javax.swing.JComboBox<String> txtIdEmpleado;
    /**
    * combo box para elegir id paquete
    */
    private javax.swing.JComboBox<String> txtIdPkt;
    /**
    * textfield para mostrar nombre del cliente
    */
    private javax.swing.JTextField txtNomCliente;
    /**
    * textfield para modificar palabra clave
    */
    private javax.swing.JTextField txtPClave;
    // End of variables declaration//GEN-END:variables
}
