/*
 * Universidad Politécnica de San Luis Potosí
 * Programación III Java 
 * Programación Orientada a Objetos
 */
package menuu;
import empleado.*;
import cliente.*;
import paquete.*;
import java.sql.Connection;

/**
 *  JFrame que proporciona al usuario una interfaz con todas las acciones que puede realizar a los empleados y paquetes
 * @author Ana Sofía Rodríguez Castillo, 178815@upslp.edu.mx
 * @author Ana Sofía Rodriguez Castillo
 * @author 178815@upslp.edu.mx
 * @version 1.0
 */
public class Menu extends javax.swing.JFrame {
    /**
     * Representa la conexión
     */
    private final Connection con;
    
    class FondoPanel extends javax.swing.JPanel{
        private java.awt.Image imagen;
        
        @Override
        public void paint(java.awt.Graphics g){
            imagen = new javax.swing.ImageIcon(
            getClass().getResource("/imgEmpleado/InicioAdmin.gif")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }

    /**
     * Creates new form Menu
     * Se crea una instancia de la clase Menu
     * Inicializa algunos de los valores que aparecen en el pane
     * Establece la posicion del pane
     * @param con Conexion
     */
    public Menu(Connection con) {
        this.con = con;
        initComponents();
        this.setTitle("Menu Administrador");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        PMenu = new FondoPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cliente = new javax.swing.JMenu();
        AltaCliente = new javax.swing.JRadioButtonMenuItem();
        ConsultaCliente = new javax.swing.JRadioButtonMenuItem();
        ModificaCliente = new javax.swing.JRadioButtonMenuItem();
        Pkt = new javax.swing.JMenu();
        AltaPkt = new javax.swing.JRadioButtonMenuItem();
        consultaPktXEmpleado = new javax.swing.JRadioButtonMenuItem();
        consultaPktXEstado = new javax.swing.JRadioButtonMenuItem();
        ModificaPkt = new javax.swing.JRadioButtonMenuItem();
        Empleado = new javax.swing.JMenu();
        AltaEmpleado = new javax.swing.JRadioButtonMenuItem();
        ConsultaEmpleado = new javax.swing.JRadioButtonMenuItem();
        ModificaEmpleado = new javax.swing.JRadioButtonMenuItem();
        Salir = new javax.swing.JMenu();
        LogOut = new javax.swing.JRadioButtonMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(710, 560));

        javax.swing.GroupLayout PMenuLayout = new javax.swing.GroupLayout(PMenu);
        PMenu.setLayout(PMenuLayout);
        PMenuLayout.setHorizontalGroup(
            PMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        PMenuLayout.setVerticalGroup(
            PMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        Cliente.setText("Cliente");

        AltaCliente.setSelected(true);
        AltaCliente.setText("Alta");
        AltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaClienteActionPerformed(evt);
            }
        });
        Cliente.add(AltaCliente);

        ConsultaCliente.setSelected(true);
        ConsultaCliente.setText("Consulta");
        ConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaClienteActionPerformed(evt);
            }
        });
        Cliente.add(ConsultaCliente);

        ModificaCliente.setSelected(true);
        ModificaCliente.setText("Modificación");
        ModificaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaClienteActionPerformed(evt);
            }
        });
        Cliente.add(ModificaCliente);

        jMenuBar1.add(Cliente);

        Pkt.setText("Paquete");

        AltaPkt.setSelected(true);
        AltaPkt.setText("Alta");
        AltaPkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaPktActionPerformed(evt);
            }
        });
        Pkt.add(AltaPkt);

        consultaPktXEmpleado.setSelected(true);
        consultaPktXEmpleado.setText("Paquetes X Empleado");
        consultaPktXEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPktXEmpleadoActionPerformed(evt);
            }
        });
        Pkt.add(consultaPktXEmpleado);

        consultaPktXEstado.setSelected(true);
        consultaPktXEstado.setText("Paquetes X Estado");
        consultaPktXEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPktXEstadoActionPerformed(evt);
            }
        });
        Pkt.add(consultaPktXEstado);

        ModificaPkt.setSelected(true);
        ModificaPkt.setText("Modificación");
        ModificaPkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaPktActionPerformed(evt);
            }
        });
        Pkt.add(ModificaPkt);

        jMenuBar1.add(Pkt);

        Empleado.setText("Empleado");

        AltaEmpleado.setSelected(true);
        AltaEmpleado.setText("Alta");
        AltaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaEmpleadoActionPerformed(evt);
            }
        });
        Empleado.add(AltaEmpleado);

        ConsultaEmpleado.setSelected(true);
        ConsultaEmpleado.setText("Consulta");
        ConsultaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaEmpleadoActionPerformed(evt);
            }
        });
        Empleado.add(ConsultaEmpleado);

        ModificaEmpleado.setSelected(true);
        ModificaEmpleado.setText("Modificación");
        ModificaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaEmpleadoActionPerformed(evt);
            }
        });
        Empleado.add(ModificaEmpleado);

        jMenuBar1.add(Empleado);

        Salir.setText("Salir");

        LogOut.setSelected(true);
        LogOut.setText("Log out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        Salir.add(LogOut);

        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AltaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaEmpleadoActionPerformed
         new AltaEmpleado(con).setVisible(true);
    }//GEN-LAST:event_AltaEmpleadoActionPerformed

    private void ConsultaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaEmpleadoActionPerformed
        new ConsultaEmpleado(con).setVisible(true);
    }//GEN-LAST:event_ConsultaEmpleadoActionPerformed

    private void AltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaClienteActionPerformed
        new AltaCliente(con).setVisible(true);
    }//GEN-LAST:event_AltaClienteActionPerformed

    private void ConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaClienteActionPerformed
        new ConsultaCliente(con).setVisible(true);
    }//GEN-LAST:event_ConsultaClienteActionPerformed

    private void ModificaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaEmpleadoActionPerformed
        new ModificaEmpleado(con).setVisible(true);
    }//GEN-LAST:event_ModificaEmpleadoActionPerformed

    private void ModificaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaClienteActionPerformed
        new ModificaCliente(con).setVisible(true);
    }//GEN-LAST:event_ModificaClienteActionPerformed

    private void AltaPktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaPktActionPerformed
        new AltaPkt(con).setVisible(true);
    }//GEN-LAST:event_AltaPktActionPerformed

    private void consultaPktXEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPktXEmpleadoActionPerformed
        new ConsultaPktXEmpleado(con).setVisible(true);
    }//GEN-LAST:event_consultaPktXEmpleadoActionPerformed

    private void consultaPktXEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPktXEstadoActionPerformed
        new ConsultaPktXEstado(con).setVisible(true);
    }//GEN-LAST:event_consultaPktXEstadoActionPerformed

    private void ModificaPktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaPktActionPerformed
        new ModificaPkt(con).setVisible(true);
    }//GEN-LAST:event_ModificaPktActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        this.dispose();
        new Login(con).setVisible(true);
    }//GEN-LAST:event_LogOutActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
    * radio button para acceder al frame de alta
    */
    private javax.swing.JRadioButtonMenuItem AltaCliente;
    /**
    * radio button para acceder al frame de alta
    */
    private javax.swing.JRadioButtonMenuItem AltaEmpleado;
    /**
    * radio button para acceder al frame de alta
    */
    private javax.swing.JRadioButtonMenuItem AltaPkt;
    /**
    * Pestaña cliente
    */
    private javax.swing.JMenu Cliente;
    /**
    * radio button para acceder al frame de consulta
    */
    private javax.swing.JRadioButtonMenuItem ConsultaCliente;
    /**
    * radio button para acceder al frame de consulta
    */
    private javax.swing.JRadioButtonMenuItem ConsultaEmpleado;
    /**
    * Pestaña empleado
    */
    private javax.swing.JMenu Empleado;
    /**
    * radio button para acceder al frame de Login
    */
    private javax.swing.JRadioButtonMenuItem LogOut;
    /**
    * radio button para acceder al frame de modificación
    */
    private javax.swing.JRadioButtonMenuItem ModificaCliente;
    /**
    * radio button para acceder al frame de modificación
    */
    private javax.swing.JRadioButtonMenuItem ModificaEmpleado;
    /**
    * radio button para acceder al frame de modificación
    */
    private javax.swing.JRadioButtonMenuItem ModificaPkt;
    /**
    * Fondo del menú
    */
    private javax.swing.JPanel PMenu;
    /**
    * Pestaña paquete
    */
    private javax.swing.JMenu Pkt;
    /**
    * Pestaña salir
    */
    private javax.swing.JMenu Salir;
    /**
    * radio button para acceder al frame de consulta por empleado
    */
    private javax.swing.JRadioButtonMenuItem consultaPktXEmpleado;
    /**
    * radio button para acceder al frame de consulta por estado del paquete
    */
    private javax.swing.JRadioButtonMenuItem consultaPktXEstado;
    /**
    * Menú
    */
    private javax.swing.JMenu jMenu1;
    /**
    * Menu barr
    */
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
